apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stage-apps
  namespace: flux-system
spec:
  interval: 1m
  path: "./config/clusters/stage-devblog" 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system 
