apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: stage-devblog
  namespace: flux-system
spec:
  interval: 5m
  path: "./config/clusters/stage-devblog"
  prune: true
  sourceRef:
    kind: GitRepository
    name: stage-devblog
  validation: client
